application: eldoactive
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:

- url: /css
  static_dir: css
  secure: always

- url: /js
  static_dir: js
  secure: always

- url: /img
  static_dir: img
  secure: always

- url: /
  static_files: index.html
  upload: index.html
  secure: always

- url: /projects
  static_dir: projects
  secure: always

- url: /resume.html
  static_files: resume.html
  upload: resume.html
  secure: always

- url: /ChristianMcCarthy_WebEngineer.pdf
  static_files: ChristianMcCarthy_WebEngineer.pdf
  upload: ChristianMcCarthy_WebEngineer.pdf
  secure: always
